const PRODUCTS = [
  {
    id: 'milk-1l',
    name: 'Volle melk 1L',
    category: 'Zuivel',
    barcode: '8712345678901',
    unit: '1L',
    price: 1.5,
    currency: 'EUR',
    suggestedDestination: 'Koelkast',
    fallbackDestination: 'Opslag',
    reason: 'Verse melk moet gekoeld blijven',
    confidence: 0.95,
    requiresPayment: true,
    auditLabel: 'Zuivel - Koeling vereist',
  },
  {
    id: 'bread-white',
    name: 'Wit brood',
    category: 'Bakkerij',
    barcode: '8712345678902',
    unit: '1 stuk',
    price: 2.2,
    currency: 'EUR',
    suggestedDestination: 'Bakkerij afdeling',
    fallbackDestination: 'Algemene opslag',
    reason: 'Brood moet droog en koel bewaard worden',
    confidence: 0.9,
    requiresPayment: true,
    auditLabel: 'Bakkerij - Droge opslag',
  },
  {
    id: 'apples-red',
    name: 'Rode appels',
    category: 'Fruit',
    barcode: '8712345678903',
    unit: '1kg',
    price: 3.0,
    currency: 'EUR',
    suggestedDestination: 'Fruit koeling',
    fallbackDestination: 'Koelcel',
    reason: 'Appels blijven langer vers in koeling',
    confidence: 0.85,
    requiresPayment: true,
    auditLabel: 'Fruit - Koeling aanbevolen',
  },
  {
    id: 'chicken-breast',
    name: 'Kipfilet',
    category: 'Vlees',
    barcode: '8712345678904',
    unit: '500g',
    price: 5.5,
    currency: 'EUR',
    suggestedDestination: 'Vlees koeling',
    fallbackDestination: 'Diepvries',
    reason: 'Vlees moet gekoeld of bevroren worden',
    confidence: 0.95,
    requiresPayment: true,
    auditLabel: 'Vlees - Koeling verplicht',
  },
  {
    id: 'pasta-spaghetti',
    name: 'Spaghetti',
    category: 'Pasta',
    barcode: '8712345678905',
    unit: '500g',
    price: 1.8,
    currency: 'EUR',
    suggestedDestination: 'Droogwaren',
    fallbackDestination: 'Algemene opslag',
    reason: 'Pasta kan op kamertemperatuur bewaard worden',
    confidence: 0.8,
    requiresPayment: true,
    auditLabel: 'Pasta - Droge opslag',
  },
  {
    id: 'yogurt-plain',
    name: 'Naturel yoghurt',
    category: 'Zuivel',
    barcode: '8712345678906',
    unit: '500g',
    price: 1.2,
    currency: 'EUR',
    suggestedDestination: 'Koelkast',
    fallbackDestination: 'Opslag',
    reason: 'Yoghurt moet gekoeld blijven',
    confidence: 0.9,
    requiresPayment: true,
    auditLabel: 'Zuivel - Koeling vereist',
  },
  {
    id: 'cheese-gouda',
    name: 'Gouda kaas',
    category: 'Zuivel',
    barcode: '8712345678907',
    unit: '200g',
    price: 3.5,
    currency: 'EUR',
    suggestedDestination: 'Kaas koeling',
    fallbackDestination: 'Koelkast',
    reason: 'Kaas blijft langer goed in koeling',
    confidence: 0.85,
    requiresPayment: true,
    auditLabel: 'Zuivel - Koeling aanbevolen',
  },
  {
    id: 'tomatoes',
    name: 'Tomaten',
    category: 'Groente',
    barcode: '8712345678908',
    unit: '1kg',
    price: 2.5,
    currency: 'EUR',
    suggestedDestination: 'Groente koeling',
    fallbackDestination: 'Koelcel',
    reason: 'Tomaten blijven vers in koeling',
    confidence: 0.8,
    requiresPayment: true,
    auditLabel: 'Groente - Koeling aanbevolen',
  },
  {
    id: 'salmon-fillet',
    name: 'Zalmfilet',
    category: 'Vis',
    barcode: '8712345678909',
    unit: '300g',
    price: 8.0,
    currency: 'EUR',
    suggestedDestination: 'Vis koeling',
    fallbackDestination: 'Diepvries',
    reason: 'Vis moet gekoeld of bevroren worden',
    confidence: 0.95,
    requiresPayment: true,
    auditLabel: 'Vis - Koeling verplicht',
  },
  {
    id: 'rice-white',
    name: 'Witte rijst',
    category: 'Granen',
    barcode: '8712345678910',
    unit: '1kg',
    price: 2.0,
    currency: 'EUR',
    suggestedDestination: 'Droogwaren',
    fallbackDestination: 'Algemene opslag',
    reason: 'Rijst kan op kamertemperatuur bewaard worden',
    confidence: 0.75,
    requiresPayment: true,
    auditLabel: 'Granen - Droge opslag',
  },
  {
    id: 'butter',
    name: 'Roomboter',
    category: 'Zuivel',
    barcode: '8712345678911',
    unit: '250g',
    price: 2.8,
    currency: 'EUR',
    suggestedDestination: 'Koelkast',
    fallbackDestination: 'Opslag',
    reason: 'Boter moet gekoeld blijven',
    confidence: 0.9,
    requiresPayment: true,
    auditLabel: 'Zuivel - Koeling vereist',
  },
  {
    id: 'bananas',
    name: 'Bananen',
    category: 'Fruit',
    barcode: '8712345678912',
    unit: '1kg',
    price: 1.8,
    currency: 'EUR',
    suggestedDestination: 'Fruit opslag',
    fallbackDestination: 'Algemene opslag',
    reason: 'Bananen kunnen op kamertemperatuur rijpen',
    confidence: 0.7,
    requiresPayment: true,
    auditLabel: 'Fruit - Kamertemperatuur',
  },
  {
    id: 'eggs-dozen',
    name: 'Eieren doos 12',
    category: 'Zuivel',
    barcode: '8712345678913',
    unit: '12 stuks',
    price: 3.2,
    currency: 'EUR',
    suggestedDestination: 'Koelkast',
    fallbackDestination: 'Koelcel',
    reason: 'Eieren blijven langer goed in koeling',
    confidence: 0.85,
    requiresPayment: true,
    auditLabel: 'Zuivel - Koeling aanbevolen',
  },
  {
    id: 'potatoes',
    name: 'Aardappelen',
    category: 'Groente',
    barcode: '8712345678914',
    unit: '2kg',
    price: 2.0,
    currency: 'EUR',
    suggestedDestination: 'Groente kelder',
    fallbackDestination: 'Donkere opslag',
    reason: 'Aardappelen moeten donker en koel bewaard worden',
    confidence: 0.8,
    requiresPayment: true,
    auditLabel: 'Groente - Donkere opslag',
  },
  {
    id: 'orange-juice',
    name: 'Sinaasappelsap',
    category: 'Dranken',
    barcode: '8712345678915',
    unit: '1L',
    price: 2.5,
    currency: 'EUR',
    suggestedDestination: 'Koelkast',
    fallbackDestination: 'Opslag',
    reason: 'Sap blijft langer goed gekoeld',
    confidence: 0.85,
    requiresPayment: true,
    auditLabel: 'Dranken - Koeling aanbevolen',
  },
];

module.exports = {
  PRODUCTS,
};